Upgrade to 1.21.4
tpwalke2/BlueMapSignMarkers pull request #82
Opened 2024-12-17 07:36 UTC by correl

- Incorporate latest fabric template for Minecraft 1.21.4
- Update Bluemap version to 5.5
- Update Bluemap API version to 2.7.3

2024-12-17 09:59 UTC, tpwalke2 commented on gradlew
Do you know why this is showing up in the PR as "empty file"? It appears that the file still exists in your repository.

2024-12-18 01:31 UTC, correl commented on gradlew
Not sure why it's showing up that way; the only changes to the file are the executable bits on it per the commit object:

```diff --git a/gradlew b/gradlew
old mode 100644
new mode 100755
```

2024-12-18 01:34 UTC, correl commented on gradlew
Looks like it's a [long-standing quirk of the Github UI](https://github.com/orgs/community/discussions/6814)

2024-12-19 01:43 UTC, tpwalke2 commented on gradlew
That's an odd issue. Thanks for sharing and for the contribution!

2024-12-19 01:43 UTC, tpwalke2 approved these changes

2024-12-19 01:48 UTC, tpwalke2 commented
@correl, it looks like there is a failure when trying to pull the bluemap api dependency in the build. Can you verify that it is using the correct path?

2024-12-19 01:49 UTC, tpwalke2 requested changes
The bluemap-api dependency is failing in the build

2024-12-19 04:46 UTC, correl commented
> @correl, it looks like there is a failure when trying to pull the bluemap api dependency in the build. Can you verify that it is using the correct path?

Yes; I got it off the current wiki: https://github.com/BlueMap-Minecraft/BlueMapAPI/wiki

The [dependency path changed for 2.7.3](https://github.com/BlueMap-Minecraft/BlueMapAPI/wiki/Home/_compare/45aa187059c3b58b5371d1403c2f249134729f88...15a2897e2520401abece2c766c29edc8ad8c0808); I had to update it to be able to build and test it locally.

2024-12-19 05:13 UTC, correl commented
Unless I'm missing something, the build error shows a failure to retrieve it from jitpack, but shouldn't it also be using the bluecolored.de repository? I'm pretty sure that's where it ought to be finding it. I'm not sure how to reproduce the failure on my machine to sort it out; Java is a bit outside of my usual wheelhouse.

2024-12-19 09:41 UTC, tpwalke2 commented
It looks like it's failing on jitpack recently: https://jitpack.io/#BlueMap-Minecraft/BlueMapAPI

I'll post a note in the BlueMap discord.

2024-12-19 09:57 UTC, tpwalke2 commented on build.gradle
BlueMap are no longer using jitpack (from Discord), instead they have their own repository: https://repo.bluecolored.de/#/releases/de/bluecolored/bluemap-api/2.7.3

I thought I had that repository configured in the `repositories` section starting on line 11. However, it may be the incorrect URL. Could you update the URL in line 18 to be `https://repo.bluecolored.de`?

2025-03-02 05:19 UTC, yqs112358 commented
Hello, any process on this PR now? :)

2025-03-02 07:15 UTC, yqs112358 commented
I have tried to merge this PR on the newest commit (with some version boosts), and the compile succeeded without any problem.
https://github.com/YQ-Fabric-Mods/BlueMapSignMarkers/commit/2f4f12d951aa4298b332bd1a5bca911f23295505

2025-03-02 10:32 UTC, tpwalke2 submitted a review, later dismissed

2025-03-02 10:36 UTC, tpwalke2 commented
@correl, I resolved a previous conflict, but the build is still failing due to deprecated github actions. Can you merge the latest from main into your branch?

2025-03-09 04:28 UTC, correl commented
Sorry for the delay; I've rebased the changes.

2025-03-09 10:50 UTC, tpwalke2 approved these changes

2025-03-09 10:50 UTC, merged

2025-03-09 10:51 UTC, tpwalke2 commented
Thank you @correl!